
# Loader Metadata
modLoader="javafml" # mandatory
loaderVersion="[31.1.39,)" # mandatory
issueTrackerURL="https://github.com/alcatrazEscapee/primal-winter/issues" # optional

# Ore Veins
[[mods]] # mandatory
    modId="primalwinter" # mandatory
    version="${file.jarVersion}" # mandatory
    displayName="Primal Winter" # mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/primalwinter" #optional FIX ME
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="AlcatrazEscapee" #optional
    description='''
    FIX ME
    '''

# dependencies
[[dependencies.primalwinter]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.primalwinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"